[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "ipywidgets>=8.1.8",
    "notebook>=7.5.6",
    "openai>=2.33.0",
    "openpyxl>=3.1.5",
    "pdfplumber>=0.11.9",
    "pillow>=12.2.0",
    "python-dotenv>=1.2.2",
    "streamlit>=1.57.0",
]
